services:
  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ai-intro
      MYSQL_USER: mysql
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
